services:
  - type: worker
    name: lz-tbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python lz_tbot.py
    envVars:
      - key: DERIV_TOKEN
        sync: false
      - key: DERIV_APP_ID
        value: 341aJK71v75g15Vud3q6w
      - key: DERIV_ACCOUNT_ID
        sync: false
      - key: SYMBOL
        value: R_75
      - key: STAKE
        value: 0.35
      - key: PYTHONUNBUFFERED
        value: 1
